# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tic_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt
import platform
import numpy as np
from PyQt5.QtWidgets import QMainWindow, QLabel, QFrame, QSizePolicy, \
    QHBoxLayout, QPushButton, QApplication
from PyQt5.QtGui import QFont
from PyQt5.QtCore import Qt, QRect, QMetaObject, QCoreApplication

system = platform.system()

selectedPoints = []
removedPointsX = []
removedPointsY = []
ticX = []
ticY = []
pickT0 = True
t0Point = [-1,-1,-1] #[xVal, yVal, indexVal]

class TICEditorGUI(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setObjectName("TIC Editor")
        self.resize(1202, 731)
        self.removePointsLabel = QLabel(self)
        self.removePointsLabel.setGeometry(QRect(410, 0, 381, 81))
        font = QFont()
        font.setPointSize(25)
        self.removePointsLabel.setFont(font)
        self.removePointsLabel.setLayoutDirection(Qt.LeftToRight)
        self.removePointsLabel.setFrameShape(QFrame.NoFrame)
        self.removePointsLabel.setFrameShadow(QFrame.Plain)
        self.removePointsLabel.setAlignment(Qt.AlignCenter)
        self.removePointsLabel.setObjectName("removePointsLabel")
        self.removePointsLabel.setHidden(True)
        self.selectT0Label = QLabel(self)
        self.selectT0Label.setGeometry(QRect(370, 0, 461, 81))
        self.selectT0Label.setFont(font)
        self.selectT0Label.setLayoutDirection(Qt.LeftToRight)
        self.selectT0Label.setFrameShape(QFrame.NoFrame)
        self.selectT0Label.setFrameShadow(QFrame.Plain)
        self.selectT0Label.setAlignment(Qt.AlignCenter)
        self.selectT0Label.setObjectName("selectT0Label")
        self.selectT0Label.setHidden(True)
        self.chooseMethodLabel = QLabel(self)
        self.chooseMethodLabel.setGeometry(QRect(370, 0, 461, 81))
        self.chooseMethodLabel.setFont(font)
        self.chooseMethodLabel.setFrameShape(QFrame.NoFrame)
        self.chooseMethodLabel.setAlignment(Qt.AlignCenter)
        self.chooseMethodLabel.setText("Select t0 selection Method")
        self.frame = QFrame(self)
        self.frame.setGeometry(QRect(50, 90, 1111, 551))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizLayout = QHBoxLayout(self.frame)
        self.fig = plt.figure()
        self.canvas = FigureCanvas(self.fig)
        self.horizLayout.addWidget(self.canvas)
        self.canvas.draw()
        self.deselect = QPushButton(self)
        self.deselect.setGeometry(QRect(50, 660, 200, 50))
        self.deselect.setText("De-Select Last Point")
        self.deselect.setFocusPolicy(Qt.NoFocus)
        self.deselect.setHidden(True)
        self.remove = QPushButton(self)
        self.remove.setGeometry(QRect(350, 660, 200, 50))
        self.remove.setText("Remove Selected Points")
        self.remove.setFocusPolicy(Qt.NoFocus)
        self.remove.setHidden(True)
        self.restore = QPushButton(self)
        self.restore.setGeometry(QRect(650,660,200,50))
        self.restore.setText("Restore Last Points")
        self.restore.setFocusPolicy(Qt.NoFocus)
        self.restore.setHidden(True)
        self.accept = QPushButton(self)
        self.accept.setGeometry(QRect(950, 660, 200, 50))
        self.accept.setText("Accept Curve")
        self.accept.setFocusPolicy(Qt.NoFocus)
        self.accept.setHidden(True)
        
        self.manualT0Button = QPushButton(self)
        self.manualT0Button.setGeometry(QRect(300, 655, 280, 60))
        self.manualT0Button.setText("Manually Select t0")
        self.manualT0Button.setFocusPolicy(Qt.NoFocus)
        self.manualT0Button.setFont(font)
        self.manualT0Button.clicked.connect(self.manualChecked)
        self.autoT0Button = QPushButton(self)
        self.autoT0Button.setGeometry(QRect(620, 655, 280, 60))
        self.autoT0Button.setText("Automatically Select t0")
        self.autoT0Button.setFocusPolicy(Qt.NoFocus)
        self.autoT0Button.setFont(font)
        self.autoT0Button.clicked.connect(self.autoChecked)

        self.acceptT0Button = QPushButton(self)
        self.acceptT0Button.setGeometry(QRect(500, 660, 200, 50))
        self.acceptT0Button.setFont(font)
        self.acceptT0Button.setText("Accept t0")
        self.acceptT0Button.setFocusPolicy(Qt.NoFocus)
        self.acceptT0Button.clicked.connect(self.acceptT0)
        self.acceptT0Button.setHidden(True)
        self.t0 = [-1,-1]
        self.frontPointsX = []
        self.frontPointsY = []

        self.deselect.clicked.connect(self.deselectLast)
        self.remove.clicked.connect(self.removeSelectedPoints)
        self.restore.clicked.connect(self.restoreLastPoints)

        self.manualPicking = False

        self.retranslateUi(self)
        QMetaObject.connectSlotsByName(self)

    def autoFindT0(self):
        if len(self.ticX) != len(self.ticY):
            print("TIC arrays must have same length!")
            return
        global t0Point
        i = 0
        while i < len(self.ticX)-1:
            if self.ticY[i+1]/self.ticY[i] > 1.1:
                t0Point = [self.ticX[i], self.ticY[i], i]
                self.acceptT0()

    def hidePickingButtons(self):
        self.manualT0Button.setHidden(True)
        self.autoT0Button.setHidden(True)
        self.chooseMethodLabel.setHidden(True)

    def manualChecked(self):
        self.manualPicking = True
        self.hidePickingButtons()
        self.acceptT0Button.setHidden(False)
        self.selectT0Label.setHidden(False)

    def displayTicEditButtons(self):
        self.accept.setHidden(False)
        self.restore.setHidden(False)
        self.remove.setHidden(False)
        self.deselect.setHidden(False)
        self.removePointsLabel.setHidden(False)
    
    def autoChecked(self):
        self.manualPicking = False
        self.hidePickingButtons()
        self.displayTicEditButtons()


    def acceptT0(self):
        global pickT0, selectedPoints, removedPointsX, removedPointsY
        if t0Point != [-1,-1,-1]:
            self.t0 = t0Point
            pickT0 = False
            self.displayTicEditButtons()
            self.acceptT0Button.setHidden(True)
            self.selectT0Label.setHidden(True)
            selectedPoints = list(range(t0Point[2]))
            self.removeSelectedPoints()
            self.frontPointsX = removedPointsX[-1]
            self.frontPointsY = removedPointsY[-1]
            removedPointsX.pop()
            removedPointsY.pop()

    def graph(self,x,y):
        global ticX, ticY
        self.ticX = x
        self.ticY = y
        ticX = self.ticX
        ticY = self.ticY
        self.ax = self.fig.add_subplot(111)
        self.ax.plot(x[:,0],y)
        self.ax.scatter(x[:,0],y,color='r')
        if system == 'Windows':
            self.ax.set_xlabel("Time (s)", fontsize=8, labelpad=0.5)
            self.ax.set_ylabel("Signal Amplitude", fontsize=8, labelpad=0.5)
            self.ax.set_title("Time Intensity Curve (TIC)", fontsize=10, pad=1.5)
            self.ax.tick_params('both', pad=0.3, labelsize=7.2)
            plt.xticks(fontsize=6)
            plt.yticks(fontsize=6)
        else:
            self.ax.set_xlabel("Time (s)", fontsize=8, labelpad=0.5)
            self.ax.set_ylabel("Signal Amplitude", fontsize=8, labelpad=0.5)
            self.ax.set_title("Time Intensity Curve (TIC)", fontsize=10, pad=1.5)
            self.ax.tick_params('both', pad=0.3, labelsize=7.2)
            plt.xticks(fontsize=3)
            plt.yticks(fontsize=3)
        self.fig.subplots_adjust(left=0.1, right=0.97, top=0.9, bottom=0.1)
        image, =self.ax.plot([], [], marker="o",markersize=3, markerfacecolor="red")
        self.cid = image.figure.canvas.mpl_connect('button_press_event', onSelect)
        self.canvas.draw()

    def deselectLast(self):
        global selectedPoints
        if len(selectedPoints) > 0:
            lastPt = selectedPoints[-1]
            selectedPoints.pop()
            self.ax.scatter(self.ticX[lastPt][0],self.ticY[lastPt],color='red')
            self.canvas.draw()

    def removeSelectedPoints(self):
        global selectedPoints, removedPointsX, removedPointsY, ticX, ticY
        if len(selectedPoints) > 0:
            selectedPoints.sort()
            j = 0
            curRemovedX = []
            curRemovedY = []
            for i in range(len(self.ticX)):
                if i == selectedPoints[j]:
                    curRemovedX.append(ticX[i])
                    curRemovedY.append(ticY[i])
                    j += 1
                    if j == len(selectedPoints):
                        break
            self.ticX = np.delete(self.ticX, selectedPoints, axis=0)
            self.ticY = np.delete(self.ticY, selectedPoints)
            # for i in range(len(selectedPoints)):
            #     ticX = np.delete(ticX,selectedPoints[i]-i)
            #     del ticY[selectedPoints[i]-1]
            self.fig.clear()
            self.graph(self.ticX,self.ticY)
            ticX = self.ticX
            ticY = self.ticY
            removedPointsX.append(curRemovedX)
            removedPointsY.append(curRemovedY)
            selectedPoints = []

    def restoreLastPoints(self):
        global selectedPoints, removedPointsX, removedPointsY, ticX, ticY
        if len(removedPointsX) > 0:
            for i in range(len(selectedPoints)):
                self.deselectLast()
            selectedPoints = []
            j = 0
            i = 0
            max = self.ticX.shape[0] + len(removedPointsX[-1])
            # removed_points = [(removedPointsX[-1][i], removedPointsY[-1][i]) for i in range(len(removedPointsX[-1]))]
            # removed_points.sort()
            while i < self.ticX.shape[0]-1:
                if self.ticX[i][0] < removedPointsX[-1][j][0] and removedPointsX[-1][j][0] < self.ticX[i+1][0]:
                    self.ticX = np.insert(self.ticX, i+1, removedPointsX[-1][j], axis=0)
                    self.ticY = np.insert(self.ticY, i+1, removedPointsY[-1][j])
                    j += 1
                    if j == len(removedPointsX[-1]):
                        break
                i += 1
            if i < max and j < len(removedPointsX[-1]):
                while j < len(removedPointsX[-1]):
                    self.ticX = np.insert(self.ticX, i+1, removedPointsX[-1][j], axis=0)
                    self.ticY = np.append(self.ticY, removedPointsY[-1][j])
                    j += 1
                    i += 1
            removedPointsX.pop()
            removedPointsY.pop()
            self.fig.clear()
            ticX = self.ticX
            ticY = self.ticY
            self.graph(ticX, ticY)

        

    def retranslateUi(self, roughGUI):
        _translate = QCoreApplication.translate
        roughGUI.setWindowTitle(_translate("TIC Editor", "TIC Editor"))
        self.removePointsLabel.setText(_translate("TIC Editor", "Select Points to Remove from TIC:"))
        self.selectT0Label.setText(_translate("TIC Editor", "Select Point to be T0 and to Start Analysis"))

def onSelect(event): # Update ROI window selected after computation
    global selectedPoints, t0Point
    for i in range(len(ticX)):
        curDiffX =  ticX[i][0] - event.xdata
        curDiffY = ticY[i] - event.ydata
        absDif = np.sqrt(curDiffX**2 + curDiffY**2)
        if absDif < 2:
            if pickT0:
                if t0Point != [-1,-1, -1]:
                    event.inaxes.scatter(t0Point[0], t0Point[1], color='red')
                event.inaxes.scatter(ticX[i][0], ticY[i], color='green')
                t0Point = [ticX[i][0], ticY[i], i]
            else:
                event.inaxes.scatter(ticX[i][0], ticY[i], color='orange')
                selectedPoints.append(i)
            break
    event.inaxes.figure.canvas.draw()

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    ui = TICEditorGUI()
    ui.show()
    sys.exit(app.exec_())