# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'initial_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QLabel, QPushButton, QMainWindow, QFrame
from PyQt5.QtCore import QRect, Qt, QMetaObject, QCoreApplication
from PyQt5.QtGui import QFont
from UtcAnalysis.utc2dController import Utc2dController
from Contrast3dAnalysis.analysis3dController import Contrast3dAnalysisController


class WelcomeGUI(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setObjectName("QUS Analysis Tools")
        self.resize(1202, 731)
        self.analysisSelectionLabel = QLabel(self)
        self.analysisSelectionLabel.setGeometry(QRect(421, 20, 361, 81))
        font = QFont()
        font.setPointSize(25)
        self.analysisSelectionLabel.setFont(font)
        self.analysisSelectionLabel.setLayoutDirection(Qt.LeftToRight)
        self.analysisSelectionLabel.setFrameShape(QFrame.NoFrame)
        self.analysisSelectionLabel.setFrameShadow(QFrame.Plain)
        self.analysisSelectionLabel.setAlignment(Qt.AlignCenter)
        self.analysisSelectionLabel.setObjectName("label")
        self.UTCDataAnalysis = QPushButton(self)
        self.UTCDataAnalysis.setGeometry(QRect(359, 210, 491, 71))
        self.UTCDataAnalysis.setFocusPolicy(Qt.NoFocus)
        font = QFont()
        font.setPointSize(20)
        self.UTCDataAnalysis.setFont(font)
        self.UTCDataAnalysis.setObjectName("UTCDataAnalysis")
        self.contrast2d = QPushButton(self)
        self.contrast2d.setGeometry(QRect(359, 360, 491, 71))
        self.contrast2d.setFocusPolicy(Qt.NoFocus)
        font = QFont()
        font.setPointSize(20)
        self.contrast2d.setFont(font)
        self.contrast2d.setObjectName("contrast2d")
        self.contrast3d = QPushButton(self)
        self.contrast3d.setGeometry(QRect(359, 510, 491, 71))
        self.contrast3d.setFocusPolicy(Qt.NoFocus)
        font = QFont()
        font.setPointSize(20)
        self.contrast3d.setFont(font)
        self.contrast3d.setObjectName("contrast3d")

        self.retranslateUi(self)
        QMetaObject.connectSlotsByName(self)
        self.UTCDataAnalysis.clicked.connect(self.switchToUTC)
        self.contrast3d.clicked.connect(self.switchTo3d)
    
    def switchTo3d(self):
        self.contrast3dUI = Contrast3dAnalysisController()
        self.contrast3dUI.show()
        self.close()

    def switchToUTC(self):
        self.utcUI = Utc2dController()
        self.utcUI.show()
        self.close()

    def retranslateUi(self, welcomeUI):
        _translate = QCoreApplication.translate
        welcomeUI.setWindowTitle(_translate("QUS Analysis Tools", "QUS Analysis Tools"))
        self.analysisSelectionLabel.setText(_translate("QUS Analysis Tools", "Select Analysis Type:"))
        self.UTCDataAnalysis.setText(_translate("QUS Analysis Tools", "UTC/RF Data Analysis"))
        self.contrast2d.setText(_translate("QUS Analysis Tools", "2D Contrast Analysis"))
        self.contrast3d.setText(_translate("QUS Analysis Tools", "3D Contrast Analysis"))
