function draw_roi_windows(hAxes, ROI_positions)
    axes(hAxes);
    % plot ROI boxes on top of B-mode image
    for n = 1:length(ROI_positions.left)
        line([ROI_positions.left(n) ROI_positions.right(n)], ...
                [ROI_positions.top(n) ROI_positions.top(n)], ...
                'Color', 'g', 'LineWidth', 0.5, 'LineStyle', '-' );
        line([ROI_positions.right(n) ROI_positions.right(n)], ...
                [ROI_positions.top(n) ROI_positions.bottom(n)], ...
                'Color', 'g', 'LineWidth', 0.5, 'LineStyle', '-' );
        line([ROI_positions.left(n) ROI_positions.right(n)], ...
                [ROI_positions.bottom(n) ROI_positions.bottom(n)], ...
                'Color', 'g', 'LineWidth', 0.5, 'LineStyle', '-' );
        line([ROI_positions.left(n) ROI_positions.left(n)], ...
                [ROI_positions.top(n) ROI_positions.bottom(n)], ...
                'Color', 'g', 'LineWidth', 0.5, 'LineStyle', '-' );
    end;  % End:  for n = 1:length(ROI_positions.left)
end