function [dbParams,  numFileHeaderBytes]= parseFileHeader(fid, endianness)
% For use with RF capture files with file headers
%       dbParams = parseFileHeader(fid, endianness)
%
% Parses for file header info
% 
% Input: fid
%   file handler
%
%
% Output: dbParams
%   Struct containing dbParameters. Should match feclib::RFCaptureDBInfo
%
% Last Modified 01/26/2018 (Dat Nguyen)
% Last Modified 09/04/2019 (Mona Shrestha)
% Last Modified 02/05/2021 (Minghe Ren)
% Added case 6
fileVersion = fread(fid,1,'ulong', endianness);
numFileHeaderBytes = fread(fid,1,'uint32', endianness);
fprintf('\tFile Version: %u\n\tHeader Size: %u bytes\n', fileVersion, numFileHeaderBytes)

%% Handle accordingly to fileVersion
switch fileVersion
    case 2,
        acqNumActiveScChannels2d = fread(fid, 4, 'uint32', endianness);
        azimuthMultilineFactorXbrOut = fread(fid, 4, 'uint32', endianness);
        azimuthMultilineFactorXbrIn = fread(fid, 4, 'uint32', endianness);
        numOfSonoCTAngles2dActual = fread(fid, 4, 'uint32', endianness);
        elevationMultilineFactor = fread(fid, 4, 'uint32', endianness);
        numPiPulses = fread(fid, 4, 'uint32', endianness);
        num2dCols = fread(fid, [14, 11], 'uint32', endianness);
        fastPiEnabled = fread(fid, 4, 'uint32', endianness);
        numZones2d = fread(fid, 4, 'uint32', endianness);
        numSubVols = fread(fid, 1, 'uint32', endianness);
        numPlanes = fread(fid, 1, 'uint32', endianness);
        zigZagEnabled = fread(fid, 1, 'uint32', endianness);
        

        dbParams = struct('acqNumActiveScChannels2d', acqNumActiveScChannels2d, ...
                           'azimuthMultilineFactorXbrOut', azimuthMultilineFactorXbrOut, ...
                           'azimuthMultilineFactorXbrIn', azimuthMultilineFactorXbrIn, ...
                           'numOfSonoCTAngles2dActual', numOfSonoCTAngles2dActual, ...
                           'elevationMultilineFactor', elevationMultilineFactor, ...
                           'numPiPulses', numPiPulses, ...
                           'num2dCols', num2dCols, ...
                           'fastPiEnabled', fastPiEnabled, ...
                           'numZones2d', numZones2d, ...
                           'numSubVols', numSubVols, ...
                           'numPlanes', numPlanes, ...
                           'zigZagEnabled', zigZagEnabled);
    case 3,
        acqNumActiveScChannels2d = fread(fid, 4, 'uint32', endianness);
        azimuthMultilineFactorXbrOut = fread(fid, 4, 'uint32', endianness);
        azimuthMultilineFactorXbrIn = fread(fid, 4, 'uint32', endianness);
        numOfSonoCTAngles2dActual = fread(fid, 4, 'uint32', endianness);
        elevationMultilineFactor = fread(fid, 4, 'uint32', endianness);
        numPiPulses = fread(fid, 4, 'uint32', endianness);
        num2dCols = fread(fid, [14, 11], 'uint32', endianness);
        fastPiEnabled = fread(fid, 4, 'uint32', endianness);
        numZones2d = fread(fid, 4, 'uint32', endianness);
        numSubVols = fread(fid, 1, 'uint32', endianness);
        numPlanes = fread(fid, 1, 'uint32', endianness);
        zigZagEnabled = fread(fid, 1, 'uint32', endianness);
        multiLineFactorCf = fread(fid, 4, 'uint32', endianness);
        linesPerEnsCf = fread(fid, 4, 'uint32', endianness);
        ensPerSeqCf = fread(fid, 4, 'uint32', endianness);
        numCfCols = fread(fid, 14, 'uint32', endianness);
        numCfEntries = fread(fid, 4, 'uint32', endianness);
        numCfDummies = fread(fid, 4, 'uint32', endianness);      

        
        dbParams = struct('acqNumActiveScChannels2d', acqNumActiveScChannels2d, ...
                           'azimuthMultilineFactorXbrOut', azimuthMultilineFactorXbrOut, ...
                           'azimuthMultilineFactorXbrIn', azimuthMultilineFactorXbrIn, ...
                           'numOfSonoCTAngles2dActual', numOfSonoCTAngles2dActual, ...
                           'elevationMultilineFactor', elevationMultilineFactor, ...
                           'numPiPulses', numPiPulses, ...
                           'num2dCols', num2dCols, ...
                           'fastPiEnabled', fastPiEnabled, ...
                           'numZones2d', numZones2d, ...
                           'numSubVols', numSubVols, ...
                           'numPlanes', numPlanes, ...
                           'zigZagEnabled', zigZagEnabled, ...
                           'multiLineFactorCf', multiLineFactorCf, ...
                           'linesPerEnsCf', linesPerEnsCf, ...
                           'ensPerSeqCf', ensPerSeqCf, ...
                           'numCfCols', numCfCols, ...
                           'numCfEntries', numCfEntries, ...
                           'numCfDummies', numCfDummies);                       
    case 4,
        acqNumActiveScChannels2d = fread(fid, 3, 'uint32', endianness);
        azimuthMultilineFactorXbrOut = fread(fid, 3, 'uint32', endianness);
        azimuthMultilineFactorXbrIn = fread(fid, 3, 'uint32', endianness);
        azimuthMultilineFactorXbrOutCf = fread(fid, 3, 'uint32', endianness);
        azimuthMultilineFactorXbrInCf = fread(fid, 3, 'uint32', endianness);
        numOfSonoCTAngles2dActual = fread(fid, 3, 'uint32', endianness);
        elevationMultilineFactor = fread(fid, 3, 'uint32', endianness);
        elevationMultilineFactorCf = fread(fid, 3, 'uint32', endianness);
        numPiPulses = fread(fid, 3, 'uint32', endianness);
        num2dCols = fread(fid, [14, 11], 'uint32', endianness);
        fastPiEnabled = fread(fid, 3, 'uint32', endianness);
        numZones2d = fread(fid, 3, 'uint32', endianness);
        numSubVols = fread(fid, 1, 'uint32', endianness);
        numPlanes = fread(fid, 1, 'uint32', endianness);
        zigZagEnabled = fread(fid, 1, 'uint32', endianness);
        linesPerEnsCf = fread(fid, 3, 'uint32', endianness);
        ensPerSeqCf = fread(fid, 3, 'uint32', endianness);
        numCfCols = fread(fid, 14, 'uint32', endianness);
        numCfEntries = fread(fid, 3, 'uint32', endianness);
        numCfDummies = fread(fid, 3, 'uint32', endianness);      

        
        dbParams = struct('acqNumActiveScChannels2d', acqNumActiveScChannels2d, ...
                           'azimuthMultilineFactorXbrOut', azimuthMultilineFactorXbrOut, ...
                           'azimuthMultilineFactorXbrIn', azimuthMultilineFactorXbrIn, ...
                           'azimuthMultilineFactorXbrOutCf', azimuthMultilineFactorXbrOutCf, ...
                           'azimuthMultilineFactorXbrInCf', azimuthMultilineFactorXbrInCf, ...
                           'numOfSonoCTAngles2dActual', numOfSonoCTAngles2dActual, ...
                           'elevationMultilineFactor', elevationMultilineFactor, ...
                           'elevationMultilineFactorCf', elevationMultilineFactorCf, ...
                           'numPiPulses', numPiPulses, ...
                           'num2dCols', num2dCols, ...
                           'fastPiEnabled', fastPiEnabled, ...
                           'numZones2d', numZones2d, ...
                           'numSubVols', numSubVols, ...
                           'numPlanes', numPlanes, ...
                           'zigZagEnabled', zigZagEnabled, ...
                           'linesPerEnsCf', linesPerEnsCf, ...
                           'ensPerSeqCf', ensPerSeqCf, ...
                           'numCfCols', numCfCols, ...
                           'numCfEntries', numCfEntries, ...
                           'numCfDummies', numCfDummies);
        case 5,
        acqNumActiveScChannels2d = fread(fid, 3, 'uint32', endianness);
        azimuthMultilineFactorXbrOut = fread(fid, 3, 'uint32', endianness);
        azimuthMultilineFactorXbrIn = fread(fid, 3, 'uint32', endianness);
        azimuthMultilineFactorXbrOutCf = fread(fid, 3, 'uint32', endianness);
        azimuthMultilineFactorXbrInCf = fread(fid, 3, 'uint32', endianness);
        numOfSonoCTAngles2dActual = fread(fid, 3, 'uint32', endianness);
        elevationMultilineFactor = fread(fid, 3, 'uint32', endianness);
        elevationMultilineFactorCf = fread(fid, 3, 'uint32', endianness);
        multiLineFactorCf = fread(fid, 3, 'uint32', endianness);
        numPiPulses = fread(fid, 3, 'uint32', endianness);
        num2dCols = fread(fid, [14, 11], 'uint32', endianness);
        fastPiEnabled = fread(fid, 3, 'uint32', endianness);
        numZones2d = fread(fid, 3, 'uint32', endianness);
        numSubVols = fread(fid, 1, 'uint32', endianness);
        numPlanes = fread(fid, 1, 'uint32', endianness);
        zigZagEnabled = fread(fid, 1, 'uint32', endianness);
        linesPerEnsCf = fread(fid, 3, 'uint32', endianness);
        ensPerSeqCf = fread(fid, 3, 'uint32', endianness);
        numCfCols = fread(fid, 14, 'uint32', endianness);
        numCfEntries = fread(fid, 3, 'uint32', endianness);
        numCfDummies = fread(fid, 3, 'uint32', endianness);      

        
        dbParams = struct('acqNumActiveScChannels2d', acqNumActiveScChannels2d, ...
                           'azimuthMultilineFactorXbrOut', azimuthMultilineFactorXbrOut, ...
                           'azimuthMultilineFactorXbrIn', azimuthMultilineFactorXbrIn, ...
                           'azimuthMultilineFactorXbrOutCf', azimuthMultilineFactorXbrOutCf, ...
                           'azimuthMultilineFactorXbrInCf', azimuthMultilineFactorXbrInCf, ...
                           'numOfSonoCTAngles2dActual', numOfSonoCTAngles2dActual, ...
                           'elevationMultilineFactor', elevationMultilineFactor, ...
                           'elevationMultilineFactorCf', elevationMultilineFactorCf, ...
                           'multiLineFactorCf', multiLineFactorCf, ...
                           'numPiPulses', numPiPulses, ...
                           'num2dCols', num2dCols, ...
                           'fastPiEnabled', fastPiEnabled, ...
                           'numZones2d', numZones2d, ...
                           'numSubVols', numSubVols, ...
                           'numPlanes', numPlanes, ...
                           'zigZagEnabled', zigZagEnabled, ...
                           'linesPerEnsCf', linesPerEnsCf, ...
                           'ensPerSeqCf', ensPerSeqCf, ...
                           'numCfCols', numCfCols, ...
                           'numCfEntries', numCfEntries, ...
                           'numCfDummies', numCfDummies);
                       
        case 6,
        tapPoint = fread(fid, 1, 'uint32', endianness);
        acqNumActiveScChannels2d = fread(fid, 3, 'uint32', endianness);
        azimuthMultilineFactorXbrOut = fread(fid, 3, 'uint32', endianness);
        azimuthMultilineFactorXbrIn = fread(fid, 3, 'uint32', endianness);
        azimuthMultilineFactorXbrOutCf = fread(fid, 3, 'uint32', endianness);
        azimuthMultilineFactorXbrInCf = fread(fid, 3, 'uint32', endianness);
        numOfSonoCTAngles2dActual = fread(fid, 3, 'uint32', endianness);
        elevationMultilineFactor = fread(fid, 3, 'uint32', endianness);
        elevationMultilineFactorCf = fread(fid, 3, 'uint32', endianness);
        multiLineFactorCf = fread(fid, 3, 'uint32', endianness);
        numPiPulses = fread(fid, 3, 'uint32', endianness);
        num2dCols = fread(fid, [14, 11], 'uint32', endianness);
        fastPiEnabled = fread(fid, 3, 'uint32', endianness);
        numZones2d = fread(fid, 3, 'uint32', endianness);
        numSubVols = fread(fid, 1, 'uint32', endianness);
        numPlanes = fread(fid, 1, 'uint32', endianness);
        zigZagEnabled = fread(fid, 1, 'uint32', endianness);
        linesPerEnsCf = fread(fid, 3, 'uint32', endianness);
        ensPerSeqCf = fread(fid, 3, 'uint32', endianness);
        numCfCols = fread(fid, 14, 'uint32', endianness);
        numCfEntries = fread(fid, 3, 'uint32', endianness);
        numCfDummies = fread(fid, 3, 'uint32', endianness);      

        
        dbParams = struct( 'tapPoint', tapPoint, ...
                           'acqNumActiveScChannels2d', acqNumActiveScChannels2d, ...
                           'azimuthMultilineFactorXbrOut', azimuthMultilineFactorXbrOut, ...
                           'azimuthMultilineFactorXbrIn', azimuthMultilineFactorXbrIn, ...
                           'azimuthMultilineFactorXbrOutCf', azimuthMultilineFactorXbrOutCf, ...
                           'azimuthMultilineFactorXbrInCf', azimuthMultilineFactorXbrInCf, ...
                           'numOfSonoCTAngles2dActual', numOfSonoCTAngles2dActual, ...
                           'elevationMultilineFactor', elevationMultilineFactor, ...
                           'elevationMultilineFactorCf', elevationMultilineFactorCf, ...
                           'multiLineFactorCf', multiLineFactorCf, ...    
                           'numPiPulses', numPiPulses, ...
                           'num2dCols', num2dCols, ...
                           'fastPiEnabled', fastPiEnabled, ...
                           'numZones2d', numZones2d, ...
                           'numSubVols', numSubVols, ...
                           'numPlanes', numPlanes, ...
                           'zigZagEnabled', zigZagEnabled, ...
                           'linesPerEnsCf', linesPerEnsCf, ...
                           'ensPerSeqCf', ensPerSeqCf, ...
                           'numCfCols', numCfCols, ...
                           'numCfEntries', numCfEntries, ...
                           'numCfDummies', numCfDummies);
    otherwise,
        dbParams = struct;
        numFileHeaderBytes = 0;
        error('Unknown file version')
end